#!/bin/bash

# Helper script para mostrar comandos de deploy
# Execute: ./scripts/deploy-help.sh

echo ""
echo "🚀 CDC Sec2 - Comandos de Deploy"
echo "=================================="
echo ""
echo "📍 Seu branch atual: $(git branch --show-current)"
echo ""
echo "🔄 WORKFLOWS DE DEPLOY:"
echo ""
echo "1️⃣  Deploy para DEVELOPMENT"
echo "   git checkout develop"
echo "   # faça suas alterações"
echo "   git add ."
echo "   git commit -m 'sua mensagem'"
echo "   npm run deploy:dev"
echo "   # ou: git push origin develop"
echo ""
echo "2️⃣  Deploy para STAGING (após testar no dev)"
echo "   git checkout staging"
echo "   git merge develop"
echo "   npm run deploy:staging"
echo "   # ou: git push origin staging"
echo ""
echo "3️⃣  Deploy para PRODUCTION (após aprovar no staging)"
echo "   git checkout main"
echo "   git merge staging"
echo "   git push origin main"
echo ""
echo "⚡ DEPLOY RÁPIDO (via Vercel CLI):"
echo ""
echo "   npm run deploy          # Preview deploy"
echo "   npm run deploy:prod     # Production deploy"
echo ""
echo "🔍 VERIFICAR STATUS:"
echo ""
echo "   vercel ls               # Lista todos os deploys"
echo "   vercel inspect          # Detalhes do último deploy"
echo ""
echo "📚 Mais informações: cat DEPLOY.md"
echo ""

